# Generated by Django 3.2.25 on 2024-11-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_auto_20241116_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_attempt', models.IntegerField(default=0)),
                ('final_result', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('IR', 'Invalid Return'), ('RTE', 'Runtime Error'), ('CE', 'Compile Error'), ('IE', 'Internal Error'), ('SC', 'Short Circuited'), ('AB', 'Aborted')], default=None, max_length=3, null=True, verbose_name='result')),
                ('problem', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='problem')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
            ],
        ),
    ]
