# Generated by Django 3.2.25 on 2024-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='identifier'),
        ),
    ]
